name: freer-simple
version: 1.2.1.1
category: Control
synopsis: Implementation of a friendly effect system for Haskell.
description: |
  An implementation of an effect system for Haskell (a fork of
  <http://hackage.haskell.org/package/freer-effects freer-effects>), which is
  based on the work of Oleg Kiselyov et al.:

    * <http://okmij.org/ftp/Haskell/extensible/more.pdf Freer Monads, More Extensible Effects>
    * <http://okmij.org/ftp/Haskell/zseq.pdf Reflection without Remorse>
    * <http://okmij.org/ftp/Haskell/extensible/exteff.pdf Extensible Effects>

  The key features are:

    * An efficient effect system for Haskell - as a library!
    * Reimplementations of several common Haskell monad transformers as effects.
    * Core components for defining your own Effects.

github: lexi-lambda/freer-simple
license: BSD3
author: Allele Dev, Ixcom Core Team, Alexis King, and other contributors
maintainer: Alexis King <lexi.lambda@gmail.com>
copyright: (c) 2016 Allele Dev; 2017 Ixperta Solutions s.r.o.; 2017 Alexis King

extra-source-files:
- CHANGELOG.md
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveFunctor
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators

dependencies:
- base >= 4.9 && < 5

library:
  source-dirs: src
  dependencies:
  - natural-transformation >= 0.2
  - transformers-base
  - template-haskell >= 2.11 && < 2.19

executables:
  freer-examples:
    source-dirs: examples/src
    main: Main.hs
    dependencies:
    - freer-simple

tests:
  unit:
    source-dirs: tests
    main: Tests.hs
    dependencies:
    - QuickCheck
    - freer-simple
    - tasty
    - tasty-hunit
    - tasty-quickcheck

benchmarks:
  core:
    source-dirs: bench
    main: Core.hs
    ghc-options: -O2
    dependencies:
    - criterion
    - extensible-effects
    - free
    - freer-simple
    - mtl
